global_costmap:
  global_frame: /minefield
  robot_base_frame: /base_link
  update_frequency: 1 #1
  publish_frequency: 3 # 3
  static_map: false
  rolling_window: true
  width: 30.0
  height: 30.0
  resolution: 0.05
