local_costmap:
  global_frame: /minefield
  robot_base_frame: /base_link
  update_frequency: 5
  publish_frequency: 2
  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
  cost_scaling_factor: 1.75
 
