obstacle_range: 3.0  #3.0
raytrace_range: 5.0  #5.0
footprint: [[0.0, 0.33], [0.55, 0.33], [0.55, -0.33], [0, -0.33], [-0.33, -0.33], [-0.33, 0.33]]
#robot_radius: 0.5

inflation_radius: 0.2

observation_sources: scan 

scan: {sensor_frame: hokuyo, data_type: LaserScan, topic: /scan, marking: true, clearing: false, inf_is_valid: true}


